// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: social_graph_service.proto

package socialgraph

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FollowUser
type FollowUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowerUserId int64                  `protobuf:"varint,1,opt,name=follower_user_id,json=followerUserId,proto3" json:"follower_user_id,omitempty"` // The user who wants to follow
	TargetUserId   int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`       // The user to be followed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_social_graph_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{0}
}

func (x *FollowUserRequest) GetFollowerUserId() int64 {
	if x != nil {
		return x.FollowerUserId
	}
	return 0
}

func (x *FollowUserRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type FollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserResponse) Reset() {
	*x = FollowUserResponse{}
	mi := &file_social_graph_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserResponse) ProtoMessage() {}

func (x *FollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserResponse.ProtoReflect.Descriptor instead.
func (*FollowUserResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{1}
}

func (x *FollowUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FollowUserResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FollowUserResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *FollowUserResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// UnfollowUser
type UnfollowUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowerUserId int64                  `protobuf:"varint,1,opt,name=follower_user_id,json=followerUserId,proto3" json:"follower_user_id,omitempty"` // The user who wants to unfollow
	TargetUserId   int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`       // The user to be unfollowed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_social_graph_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowUserRequest) GetFollowerUserId() int64 {
	if x != nil {
		return x.FollowerUserId
	}
	return 0
}

func (x *UnfollowUserRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type UnfollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserResponse) Reset() {
	*x = UnfollowUserResponse{}
	mi := &file_social_graph_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserResponse) ProtoMessage() {}

func (x *UnfollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserResponse.ProtoReflect.Descriptor instead.
func (*UnfollowUserResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnfollowUserResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UnfollowUserResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// GetFollowers
type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required: ID of the user whose followers to retrieve
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                 // Optional: Maximum number of followers to return (default: 1000)
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`               // Optional: Pagination offset (default: 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_social_graph_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetFollowersRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFollowersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`        // List of follower user IDs
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`      // Total follower count before pagination
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`               // Whether there are more results available
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if request failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_social_graph_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetFollowersResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetFollowersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetFollowersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetFollowersResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetFollowing
type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // Required: ID of the user whose following list to retrieve
	MinFollowers  int32                  `protobuf:"varint,2,opt,name=min_followers,json=minFollowers,proto3" json:"min_followers,omitempty"` // Optional: Minimum follower count filter (default: 0)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                   // Optional: Maximum number of users to return (default: 1000)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_social_graph_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetFollowingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowingRequest) GetMinFollowers() int32 {
	if x != nil {
		return x.MinFollowers
	}
	return 0
}

func (x *GetFollowingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`        // List of user IDs that the user follows
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`      // Total count before limit applied
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`               // Whether there are more results available
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if request failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_social_graph_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetFollowingResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetFollowingResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetFollowingResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetFollowingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetFollowersCount
type GetFollowersCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersCountRequest) Reset() {
	*x = GetFollowersCountRequest{}
	mi := &file_social_graph_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersCountRequest) ProtoMessage() {}

func (x *GetFollowersCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersCountRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersCountRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowersCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFollowersCountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowersCount int32                  `protobuf:"varint,2,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFollowersCountResponse) Reset() {
	*x = GetFollowersCountResponse{}
	mi := &file_social_graph_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersCountResponse) ProtoMessage() {}

func (x *GetFollowersCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersCountResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersCountResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetFollowersCountResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowersCountResponse) GetFollowersCount() int32 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

func (x *GetFollowersCountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetFollowingCount
type GetFollowingCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingCountRequest) Reset() {
	*x = GetFollowingCountRequest{}
	mi := &file_social_graph_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingCountRequest) ProtoMessage() {}

func (x *GetFollowingCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingCountRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingCountRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetFollowingCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFollowingCountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowingCount int32                  `protobuf:"varint,2,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFollowingCountResponse) Reset() {
	*x = GetFollowingCountResponse{}
	mi := &file_social_graph_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingCountResponse) ProtoMessage() {}

func (x *GetFollowingCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingCountResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingCountResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetFollowingCountResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowingCountResponse) GetFollowingCount() int32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *GetFollowingCountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// CheckFollowRelationship
type CheckFollowRelationshipRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowerUserId int64                  `protobuf:"varint,1,opt,name=follower_user_id,json=followerUserId,proto3" json:"follower_user_id,omitempty"`
	TargetUserId   int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckFollowRelationshipRequest) Reset() {
	*x = CheckFollowRelationshipRequest{}
	mi := &file_social_graph_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFollowRelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFollowRelationshipRequest) ProtoMessage() {}

func (x *CheckFollowRelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFollowRelationshipRequest.ProtoReflect.Descriptor instead.
func (*CheckFollowRelationshipRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{12}
}

func (x *CheckFollowRelationshipRequest) GetFollowerUserId() int64 {
	if x != nil {
		return x.FollowerUserId
	}
	return 0
}

func (x *CheckFollowRelationshipRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type CheckFollowRelationshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollowing   bool                   `protobuf:"varint,1,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFollowRelationshipResponse) Reset() {
	*x = CheckFollowRelationshipResponse{}
	mi := &file_social_graph_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFollowRelationshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFollowRelationshipResponse) ProtoMessage() {}

func (x *CheckFollowRelationshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFollowRelationshipResponse.ProtoReflect.Descriptor instead.
func (*CheckFollowRelationshipResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{13}
}

func (x *CheckFollowRelationshipResponse) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

func (x *CheckFollowRelationshipResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// BatchCreateFollowRelationships (for data generation)
type BatchCreateFollowRelationshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relationships []*FollowRelationship  `protobuf:"bytes,1,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateFollowRelationshipsRequest) Reset() {
	*x = BatchCreateFollowRelationshipsRequest{}
	mi := &file_social_graph_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateFollowRelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateFollowRelationshipsRequest) ProtoMessage() {}

func (x *BatchCreateFollowRelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateFollowRelationshipsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateFollowRelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{14}
}

func (x *BatchCreateFollowRelationshipsRequest) GetRelationships() []*FollowRelationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

type FollowRelationship struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowerUserId int64                  `protobuf:"varint,1,opt,name=follower_user_id,json=followerUserId,proto3" json:"follower_user_id,omitempty"`
	TargetUserId   int64                  `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowRelationship) Reset() {
	*x = FollowRelationship{}
	mi := &file_social_graph_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRelationship) ProtoMessage() {}

func (x *FollowRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRelationship.ProtoReflect.Descriptor instead.
func (*FollowRelationship) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{15}
}

func (x *FollowRelationship) GetFollowerUserId() int64 {
	if x != nil {
		return x.FollowerUserId
	}
	return 0
}

func (x *FollowRelationship) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type BatchCreateFollowRelationshipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedCount  int32                  `protobuf:"varint,1,opt,name=created_count,json=createdCount,proto3" json:"created_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateFollowRelationshipsResponse) Reset() {
	*x = BatchCreateFollowRelationshipsResponse{}
	mi := &file_social_graph_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateFollowRelationshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateFollowRelationshipsResponse) ProtoMessage() {}

func (x *BatchCreateFollowRelationshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_graph_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateFollowRelationshipsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateFollowRelationshipsResponse) Descriptor() ([]byte, []int) {
	return file_social_graph_service_proto_rawDescGZIP(), []int{16}
}

func (x *BatchCreateFollowRelationshipsResponse) GetCreatedCount() int32 {
	if x != nil {
		return x.CreatedCount
	}
	return 0
}

func (x *BatchCreateFollowRelationshipsResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BatchCreateFollowRelationshipsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchCreateFollowRelationshipsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_social_graph_service_proto protoreflect.FileDescriptor

const file_social_graph_service_proto_rawDesc = "" +
	"\n" +
	"\x1asocial_graph_service.proto\x12\vsocialgraph\"c\n" +
	"\x11FollowUserRequest\x12(\n" +
	"\x10follower_user_id\x18\x01 \x01(\x03R\x0efollowerUserId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\"\x91\x01\n" +
	"\x12FollowUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"e\n" +
	"\x13UnfollowUserRequest\x12(\n" +
	"\x10follower_user_id\x18\x01 \x01(\x03R\x0efollowerUserId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\"t\n" +
	"\x14UnfollowUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\\\n" +
	"\x13GetFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x92\x01\n" +
	"\x14GetFollowersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"i\n" +
	"\x13GetFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\rmin_followers\x18\x02 \x01(\x05R\fminFollowers\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x92\x01\n" +
	"\x14GetFollowingResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"3\n" +
	"\x18GetFollowersCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x82\x01\n" +
	"\x19GetFollowersCountResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0ffollowers_count\x18\x02 \x01(\x05R\x0efollowersCount\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"3\n" +
	"\x18GetFollowingCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x82\x01\n" +
	"\x19GetFollowingCountResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0ffollowing_count\x18\x02 \x01(\x05R\x0efollowingCount\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"p\n" +
	"\x1eCheckFollowRelationshipRequest\x12(\n" +
	"\x10follower_user_id\x18\x01 \x01(\x03R\x0efollowerUserId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\"i\n" +
	"\x1fCheckFollowRelationshipResponse\x12!\n" +
	"\fis_following\x18\x01 \x01(\bR\visFollowing\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"n\n" +
	"%BatchCreateFollowRelationshipsRequest\x12E\n" +
	"\rrelationships\x18\x01 \x03(\v2\x1f.socialgraph.FollowRelationshipR\rrelationships\"d\n" +
	"\x12FollowRelationship\x12(\n" +
	"\x10follower_user_id\x18\x01 \x01(\x03R\x0efollowerUserId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\x03R\ftargetUserId\"\xaf\x01\n" +
	"&BatchCreateFollowRelationshipsResponse\x12#\n" +
	"\rcreated_count\x18\x01 \x01(\x05R\fcreatedCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2\xac\x06\n" +
	"\x12SocialGraphService\x12M\n" +
	"\n" +
	"FollowUser\x12\x1e.socialgraph.FollowUserRequest\x1a\x1f.socialgraph.FollowUserResponse\x12S\n" +
	"\fUnfollowUser\x12 .socialgraph.UnfollowUserRequest\x1a!.socialgraph.UnfollowUserResponse\x12S\n" +
	"\fGetFollowers\x12 .socialgraph.GetFollowersRequest\x1a!.socialgraph.GetFollowersResponse\x12S\n" +
	"\fGetFollowing\x12 .socialgraph.GetFollowingRequest\x1a!.socialgraph.GetFollowingResponse\x12b\n" +
	"\x11GetFollowersCount\x12%.socialgraph.GetFollowersCountRequest\x1a&.socialgraph.GetFollowersCountResponse\x12b\n" +
	"\x11GetFollowingCount\x12%.socialgraph.GetFollowingCountRequest\x1a&.socialgraph.GetFollowingCountResponse\x12t\n" +
	"\x17CheckFollowRelationship\x12+.socialgraph.CheckFollowRelationshipRequest\x1a,.socialgraph.CheckFollowRelationshipResponse\x12\x89\x01\n" +
	"\x1eBatchCreateFollowRelationships\x122.socialgraph.BatchCreateFollowRelationshipsRequest\x1a3.socialgraph.BatchCreateFollowRelationshipsResponseBKZIgithub.com/PCBZ/CS6650-Project/services/social-graph-services/socialgraphb\x06proto3"

var (
	file_social_graph_service_proto_rawDescOnce sync.Once
	file_social_graph_service_proto_rawDescData []byte
)

func file_social_graph_service_proto_rawDescGZIP() []byte {
	file_social_graph_service_proto_rawDescOnce.Do(func() {
		file_social_graph_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_graph_service_proto_rawDesc), len(file_social_graph_service_proto_rawDesc)))
	})
	return file_social_graph_service_proto_rawDescData
}

var file_social_graph_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_social_graph_service_proto_goTypes = []any{
	(*FollowUserRequest)(nil),                      // 0: socialgraph.FollowUserRequest
	(*FollowUserResponse)(nil),                     // 1: socialgraph.FollowUserResponse
	(*UnfollowUserRequest)(nil),                    // 2: socialgraph.UnfollowUserRequest
	(*UnfollowUserResponse)(nil),                   // 3: socialgraph.UnfollowUserResponse
	(*GetFollowersRequest)(nil),                    // 4: socialgraph.GetFollowersRequest
	(*GetFollowersResponse)(nil),                   // 5: socialgraph.GetFollowersResponse
	(*GetFollowingRequest)(nil),                    // 6: socialgraph.GetFollowingRequest
	(*GetFollowingResponse)(nil),                   // 7: socialgraph.GetFollowingResponse
	(*GetFollowersCountRequest)(nil),               // 8: socialgraph.GetFollowersCountRequest
	(*GetFollowersCountResponse)(nil),              // 9: socialgraph.GetFollowersCountResponse
	(*GetFollowingCountRequest)(nil),               // 10: socialgraph.GetFollowingCountRequest
	(*GetFollowingCountResponse)(nil),              // 11: socialgraph.GetFollowingCountResponse
	(*CheckFollowRelationshipRequest)(nil),         // 12: socialgraph.CheckFollowRelationshipRequest
	(*CheckFollowRelationshipResponse)(nil),        // 13: socialgraph.CheckFollowRelationshipResponse
	(*BatchCreateFollowRelationshipsRequest)(nil),  // 14: socialgraph.BatchCreateFollowRelationshipsRequest
	(*FollowRelationship)(nil),                     // 15: socialgraph.FollowRelationship
	(*BatchCreateFollowRelationshipsResponse)(nil), // 16: socialgraph.BatchCreateFollowRelationshipsResponse
}
var file_social_graph_service_proto_depIdxs = []int32{
	15, // 0: socialgraph.BatchCreateFollowRelationshipsRequest.relationships:type_name -> socialgraph.FollowRelationship
	0,  // 1: socialgraph.SocialGraphService.FollowUser:input_type -> socialgraph.FollowUserRequest
	2,  // 2: socialgraph.SocialGraphService.UnfollowUser:input_type -> socialgraph.UnfollowUserRequest
	4,  // 3: socialgraph.SocialGraphService.GetFollowers:input_type -> socialgraph.GetFollowersRequest
	6,  // 4: socialgraph.SocialGraphService.GetFollowing:input_type -> socialgraph.GetFollowingRequest
	8,  // 5: socialgraph.SocialGraphService.GetFollowersCount:input_type -> socialgraph.GetFollowersCountRequest
	10, // 6: socialgraph.SocialGraphService.GetFollowingCount:input_type -> socialgraph.GetFollowingCountRequest
	12, // 7: socialgraph.SocialGraphService.CheckFollowRelationship:input_type -> socialgraph.CheckFollowRelationshipRequest
	14, // 8: socialgraph.SocialGraphService.BatchCreateFollowRelationships:input_type -> socialgraph.BatchCreateFollowRelationshipsRequest
	1,  // 9: socialgraph.SocialGraphService.FollowUser:output_type -> socialgraph.FollowUserResponse
	3,  // 10: socialgraph.SocialGraphService.UnfollowUser:output_type -> socialgraph.UnfollowUserResponse
	5,  // 11: socialgraph.SocialGraphService.GetFollowers:output_type -> socialgraph.GetFollowersResponse
	7,  // 12: socialgraph.SocialGraphService.GetFollowing:output_type -> socialgraph.GetFollowingResponse
	9,  // 13: socialgraph.SocialGraphService.GetFollowersCount:output_type -> socialgraph.GetFollowersCountResponse
	11, // 14: socialgraph.SocialGraphService.GetFollowingCount:output_type -> socialgraph.GetFollowingCountResponse
	13, // 15: socialgraph.SocialGraphService.CheckFollowRelationship:output_type -> socialgraph.CheckFollowRelationshipResponse
	16, // 16: socialgraph.SocialGraphService.BatchCreateFollowRelationships:output_type -> socialgraph.BatchCreateFollowRelationshipsResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_social_graph_service_proto_init() }
func file_social_graph_service_proto_init() {
	if File_social_graph_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_graph_service_proto_rawDesc), len(file_social_graph_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_graph_service_proto_goTypes,
		DependencyIndexes: file_social_graph_service_proto_depIdxs,
		MessageInfos:      file_social_graph_service_proto_msgTypes,
	}.Build()
	File_social_graph_service_proto = out.File
	file_social_graph_service_proto_goTypes = nil
	file_social_graph_service_proto_depIdxs = nil
}
