// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/social_graph_service.proto

package socialgraph

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocialGraphService_FollowUser_FullMethodName                     = "/socialgraph.SocialGraphService/FollowUser"
	SocialGraphService_UnfollowUser_FullMethodName                   = "/socialgraph.SocialGraphService/UnfollowUser"
	SocialGraphService_GetFollowers_FullMethodName                   = "/socialgraph.SocialGraphService/GetFollowers"
	SocialGraphService_GetFollowingList_FullMethodName               = "/socialgraph.SocialGraphService/GetFollowingList"
	SocialGraphService_GetFollowersCount_FullMethodName              = "/socialgraph.SocialGraphService/GetFollowersCount"
	SocialGraphService_GetFollowingCount_FullMethodName              = "/socialgraph.SocialGraphService/GetFollowingCount"
	SocialGraphService_CheckFollowRelationship_FullMethodName        = "/socialgraph.SocialGraphService/CheckFollowRelationship"
	SocialGraphService_BatchCreateFollowRelationships_FullMethodName = "/socialgraph.SocialGraphService/BatchCreateFollowRelationships"
)

// SocialGraphServiceClient is the client API for SocialGraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SocialGraphService manages follow relationships between users
type SocialGraphServiceClient interface {
	// FollowUser creates a follow relationship
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error)
	// UnfollowUser removes a follow relationship
	UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error)
	// GetFollowers retrieves the list of users who follow a specified user
	GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error)
	// GetFollowingList retrieves the list of users that a specified user follows
	GetFollowingList(ctx context.Context, in *GetFollowingListRequest, opts ...grpc.CallOption) (*GetFollowingListResponse, error)
	// GetFollowersCount retrieves the follower count for a user
	GetFollowersCount(ctx context.Context, in *GetFollowersCountRequest, opts ...grpc.CallOption) (*GetFollowersCountResponse, error)
	// GetFollowingCount retrieves the following count for a user
	GetFollowingCount(ctx context.Context, in *GetFollowingCountRequest, opts ...grpc.CallOption) (*GetFollowingCountResponse, error)
	// CheckFollowRelationship checks if a follow relationship exists
	CheckFollowRelationship(ctx context.Context, in *CheckFollowRelationshipRequest, opts ...grpc.CallOption) (*CheckFollowRelationshipResponse, error)
	// BatchCreateFollowRelationships creates multiple follow relationships (for data generation)
	BatchCreateFollowRelationships(ctx context.Context, in *BatchCreateFollowRelationshipsRequest, opts ...grpc.CallOption) (*BatchCreateFollowRelationshipsResponse, error)
}

type socialGraphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialGraphServiceClient(cc grpc.ClientConnInterface) SocialGraphServiceClient {
	return &socialGraphServiceClient{cc}
}

func (c *socialGraphServiceClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowUserResponse)
	err := c.cc.Invoke(ctx, SocialGraphService_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGraphServiceClient) UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowUserResponse)
	err := c.cc.Invoke(ctx, SocialGraphService_UnfollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGraphServiceClient) GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowersResponse)
	err := c.cc.Invoke(ctx, SocialGraphService_GetFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGraphServiceClient) GetFollowingList(ctx context.Context, in *GetFollowingListRequest, opts ...grpc.CallOption) (*GetFollowingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowingListResponse)
	err := c.cc.Invoke(ctx, SocialGraphService_GetFollowingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGraphServiceClient) GetFollowersCount(ctx context.Context, in *GetFollowersCountRequest, opts ...grpc.CallOption) (*GetFollowersCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowersCountResponse)
	err := c.cc.Invoke(ctx, SocialGraphService_GetFollowersCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGraphServiceClient) GetFollowingCount(ctx context.Context, in *GetFollowingCountRequest, opts ...grpc.CallOption) (*GetFollowingCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowingCountResponse)
	err := c.cc.Invoke(ctx, SocialGraphService_GetFollowingCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGraphServiceClient) CheckFollowRelationship(ctx context.Context, in *CheckFollowRelationshipRequest, opts ...grpc.CallOption) (*CheckFollowRelationshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckFollowRelationshipResponse)
	err := c.cc.Invoke(ctx, SocialGraphService_CheckFollowRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialGraphServiceClient) BatchCreateFollowRelationships(ctx context.Context, in *BatchCreateFollowRelationshipsRequest, opts ...grpc.CallOption) (*BatchCreateFollowRelationshipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateFollowRelationshipsResponse)
	err := c.cc.Invoke(ctx, SocialGraphService_BatchCreateFollowRelationships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialGraphServiceServer is the server API for SocialGraphService service.
// All implementations must embed UnimplementedSocialGraphServiceServer
// for forward compatibility.
//
// SocialGraphService manages follow relationships between users
type SocialGraphServiceServer interface {
	// FollowUser creates a follow relationship
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error)
	// UnfollowUser removes a follow relationship
	UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserResponse, error)
	// GetFollowers retrieves the list of users who follow a specified user
	GetFollowers(context.Context, *GetFollowersRequest) (*GetFollowersResponse, error)
	// GetFollowingList retrieves the list of users that a specified user follows
	GetFollowingList(context.Context, *GetFollowingListRequest) (*GetFollowingListResponse, error)
	// GetFollowersCount retrieves the follower count for a user
	GetFollowersCount(context.Context, *GetFollowersCountRequest) (*GetFollowersCountResponse, error)
	// GetFollowingCount retrieves the following count for a user
	GetFollowingCount(context.Context, *GetFollowingCountRequest) (*GetFollowingCountResponse, error)
	// CheckFollowRelationship checks if a follow relationship exists
	CheckFollowRelationship(context.Context, *CheckFollowRelationshipRequest) (*CheckFollowRelationshipResponse, error)
	// BatchCreateFollowRelationships creates multiple follow relationships (for data generation)
	BatchCreateFollowRelationships(context.Context, *BatchCreateFollowRelationshipsRequest) (*BatchCreateFollowRelationshipsResponse, error)
	mustEmbedUnimplementedSocialGraphServiceServer()
}

// UnimplementedSocialGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialGraphServiceServer struct{}

func (UnimplementedSocialGraphServiceServer) FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedSocialGraphServiceServer) UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfollowUser not implemented")
}
func (UnimplementedSocialGraphServiceServer) GetFollowers(context.Context, *GetFollowersRequest) (*GetFollowersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowers not implemented")
}
func (UnimplementedSocialGraphServiceServer) GetFollowingList(context.Context, *GetFollowingListRequest) (*GetFollowingListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowingList not implemented")
}
func (UnimplementedSocialGraphServiceServer) GetFollowersCount(context.Context, *GetFollowersCountRequest) (*GetFollowersCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowersCount not implemented")
}
func (UnimplementedSocialGraphServiceServer) GetFollowingCount(context.Context, *GetFollowingCountRequest) (*GetFollowingCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowingCount not implemented")
}
func (UnimplementedSocialGraphServiceServer) CheckFollowRelationship(context.Context, *CheckFollowRelationshipRequest) (*CheckFollowRelationshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFollowRelationship not implemented")
}
func (UnimplementedSocialGraphServiceServer) BatchCreateFollowRelationships(context.Context, *BatchCreateFollowRelationshipsRequest) (*BatchCreateFollowRelationshipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCreateFollowRelationships not implemented")
}
func (UnimplementedSocialGraphServiceServer) mustEmbedUnimplementedSocialGraphServiceServer() {}
func (UnimplementedSocialGraphServiceServer) testEmbeddedByValue()                            {}

// UnsafeSocialGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialGraphServiceServer will
// result in compilation errors.
type UnsafeSocialGraphServiceServer interface {
	mustEmbedUnimplementedSocialGraphServiceServer()
}

func RegisterSocialGraphServiceServer(s grpc.ServiceRegistrar, srv SocialGraphServiceServer) {
	// If the following call pancis, it indicates UnimplementedSocialGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialGraphService_ServiceDesc, srv)
}

func _SocialGraphService_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGraphServiceServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialGraphService_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGraphServiceServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGraphService_UnfollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGraphServiceServer).UnfollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialGraphService_UnfollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGraphServiceServer).UnfollowUser(ctx, req.(*UnfollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGraphService_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGraphServiceServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialGraphService_GetFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGraphServiceServer).GetFollowers(ctx, req.(*GetFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGraphService_GetFollowingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGraphServiceServer).GetFollowingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialGraphService_GetFollowingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGraphServiceServer).GetFollowingList(ctx, req.(*GetFollowingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGraphService_GetFollowersCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowersCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGraphServiceServer).GetFollowersCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialGraphService_GetFollowersCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGraphServiceServer).GetFollowersCount(ctx, req.(*GetFollowersCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGraphService_GetFollowingCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGraphServiceServer).GetFollowingCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialGraphService_GetFollowingCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGraphServiceServer).GetFollowingCount(ctx, req.(*GetFollowingCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGraphService_CheckFollowRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFollowRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGraphServiceServer).CheckFollowRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialGraphService_CheckFollowRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGraphServiceServer).CheckFollowRelationship(ctx, req.(*CheckFollowRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialGraphService_BatchCreateFollowRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateFollowRelationshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialGraphServiceServer).BatchCreateFollowRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialGraphService_BatchCreateFollowRelationships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialGraphServiceServer).BatchCreateFollowRelationships(ctx, req.(*BatchCreateFollowRelationshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialGraphService_ServiceDesc is the grpc.ServiceDesc for SocialGraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialGraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "socialgraph.SocialGraphService",
	HandlerType: (*SocialGraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FollowUser",
			Handler:    _SocialGraphService_FollowUser_Handler,
		},
		{
			MethodName: "UnfollowUser",
			Handler:    _SocialGraphService_UnfollowUser_Handler,
		},
		{
			MethodName: "GetFollowers",
			Handler:    _SocialGraphService_GetFollowers_Handler,
		},
		{
			MethodName: "GetFollowingList",
			Handler:    _SocialGraphService_GetFollowingList_Handler,
		},
		{
			MethodName: "GetFollowersCount",
			Handler:    _SocialGraphService_GetFollowersCount_Handler,
		},
		{
			MethodName: "GetFollowingCount",
			Handler:    _SocialGraphService_GetFollowingCount_Handler,
		},
		{
			MethodName: "CheckFollowRelationship",
			Handler:    _SocialGraphService_CheckFollowRelationship_Handler,
		},
		{
			MethodName: "BatchCreateFollowRelationships",
			Handler:    _SocialGraphService_BatchCreateFollowRelationships_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/social_graph_service.proto",
}
