// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/socialgraph/socialgraph.proto

package socialgraph

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFollowingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Required: User ID to get following list for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingListRequest) Reset() {
	*x = GetFollowingListRequest{}
	mi := &file_proto_socialgraph_socialgraph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingListRequest) ProtoMessage() {}

func (x *GetFollowingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_socialgraph_socialgraph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingListRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingListRequest) Descriptor() ([]byte, []int) {
	return file_proto_socialgraph_socialgraph_proto_rawDescGZIP(), []int{0}
}

func (x *GetFollowingListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFollowingListResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FollowingUserIds []int64                `protobuf:"varint,1,rep,packed,name=following_user_ids,json=followingUserIds,proto3" json:"following_user_ids,omitempty"` // List of user IDs that this user follows
	ErrorCode        string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`                                // Error code if request failed
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                       // Error message if request failed
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetFollowingListResponse) Reset() {
	*x = GetFollowingListResponse{}
	mi := &file_proto_socialgraph_socialgraph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingListResponse) ProtoMessage() {}

func (x *GetFollowingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_socialgraph_socialgraph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingListResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingListResponse) Descriptor() ([]byte, []int) {
	return file_proto_socialgraph_socialgraph_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowingListResponse) GetFollowingUserIds() []int64 {
	if x != nil {
		return x.FollowingUserIds
	}
	return nil
}

func (x *GetFollowingListResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetFollowingListResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_socialgraph_socialgraph_proto protoreflect.FileDescriptor

const file_proto_socialgraph_socialgraph_proto_rawDesc = "" +
	"\n" +
	"#proto/socialgraph/socialgraph.proto\x12\vsocialgraph\"2\n" +
	"\x17GetFollowingListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x8c\x01\n" +
	"\x18GetFollowingListResponse\x12,\n" +
	"\x12following_user_ids\x18\x01 \x03(\x03R\x10followingUserIds\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2u\n" +
	"\x12SocialGraphService\x12_\n" +
	"\x10GetFollowingList\x12$.socialgraph.GetFollowingListRequest\x1a%.socialgraph.GetFollowingListResponseBLZJgithub.com/PCBZ/CS6650-Project/services/timeline-service/proto/socialgraphb\x06proto3"

var (
	file_proto_socialgraph_socialgraph_proto_rawDescOnce sync.Once
	file_proto_socialgraph_socialgraph_proto_rawDescData []byte
)

func file_proto_socialgraph_socialgraph_proto_rawDescGZIP() []byte {
	file_proto_socialgraph_socialgraph_proto_rawDescOnce.Do(func() {
		file_proto_socialgraph_socialgraph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_socialgraph_socialgraph_proto_rawDesc), len(file_proto_socialgraph_socialgraph_proto_rawDesc)))
	})
	return file_proto_socialgraph_socialgraph_proto_rawDescData
}

var file_proto_socialgraph_socialgraph_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_socialgraph_socialgraph_proto_goTypes = []any{
	(*GetFollowingListRequest)(nil),  // 0: socialgraph.GetFollowingListRequest
	(*GetFollowingListResponse)(nil), // 1: socialgraph.GetFollowingListResponse
}
var file_proto_socialgraph_socialgraph_proto_depIdxs = []int32{
	0, // 0: socialgraph.SocialGraphService.GetFollowingList:input_type -> socialgraph.GetFollowingListRequest
	1, // 1: socialgraph.SocialGraphService.GetFollowingList:output_type -> socialgraph.GetFollowingListResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_socialgraph_socialgraph_proto_init() }
func file_proto_socialgraph_socialgraph_proto_init() {
	if File_proto_socialgraph_socialgraph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_socialgraph_socialgraph_proto_rawDesc), len(file_proto_socialgraph_socialgraph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_socialgraph_socialgraph_proto_goTypes,
		DependencyIndexes: file_proto_socialgraph_socialgraph_proto_depIdxs,
		MessageInfos:      file_proto_socialgraph_socialgraph_proto_msgTypes,
	}.Build()
	File_proto_socialgraph_socialgraph_proto = out.File
	file_proto_socialgraph_socialgraph_proto_goTypes = nil
	file_proto_socialgraph_socialgraph_proto_depIdxs = nil
}
